Master.create(code: '1.0', name: 'Condition of Working Area and Passageway', chi_name: '工作區和通道的條件', parent_id: 26)
Master.create(code: '1.2', name: 'Precautionary measures to prevent slippery harard', chi_name: '防止滑溜危險的預防措施', parent_id: 26)
Master.create(code: '2.0', name: 'LSG', chi_name: 'LSG', parent_id: 26)
Master.create(code: '2.1', name: 'Publicity board with correct information at prompt location', chi_name: '宣傳板在正確的位置提供正確的信息', parent_id: 26)
Master.create(code: '2.2', name: 'Adequate vehicular and pedestrian diversion', chi_name: '充足的車輛和行人分流', parent_id: 26)
Master.create(code: '2.3', name: 'Traffic cones/barriers to fence off working area', chi_name: '交通錐/障礙圍欄工作區', parent_id: 26)
Master.create(code: '3.0', name: 'Personal Protective Equipment', chi_name: '個人保護設備', parent_id: 26)
Master.create(code: '3.1', name: 'Safety helmets with chin strap', chi_name: '帶下巴帶的安全頭盔', parent_id: 26)
Master.create(code: '3.2', name: 'Safety Shoes or specific slope working shoes', chi_name: '安全鞋或特定斜坡工作鞋', parent_id: 26)
Master.create(code: '3.3', name: 'Eye goggles / face shield', chi_name: '護目鏡/面罩', parent_id: 26)
Master.create(code: '3.4', name: 'Ear plugs', chi_name: '耳塞', parent_id: 26)
Master.create(code: '3.5', name: 'Dust mask', chi_name: '防塵口罩', parent_id: 26)
Master.create(code: '3.6', name: 'Reflective vest', chi_name: '反光背心', parent_id: 26)
Master.create(code: '3.7', name: 'Safety harness with fall arrestor', chi_name: '帶防墜落裝置的安全帶', parent_id: 26)
Master.create(code: '3.8', name: 'Protective gloves', chi_name: '防護手套', parent_id: 26)
Master.create(code: '3.9', name: 'Chainsaw-resistant chaps', chi_name: '耐電鋸鏈條', parent_id: 26)
Master.create(code: '4.0', name: 'Working at Height / Work-above-ground/On Slope', chi_name: '在高處/斜坡上工作', parent_id: 26)
Master.create(code: '4.1', name: 'Independent lifeline', chi_name: '獨立的生命線', parent_id: 26)
Master.create(code: '4.2', name: 'Secure Anchorage Point', chi_name: '安全錨點', parent_id: 26)
Master.create(code: '5.0', name: 'Powered Aerial Working Platform', chi_name: '動力空中作業平台', parent_id: 26)
Master.create(code: '5.1', name: 'Statutory Form/Cert. (Form 1, 4 & 5)', chi_name: '法定表格/證書。 (表格1,4和5)', parent_id: 26)
Master.create(code: '5.2', name: 'All outriggers fully extended with stand pads used', chi_name: '所有支腿都使用支架墊完全伸展', parent_id: 26)
Master.create(code: '5.3', name: 'Trained Operator', chi_name: '訓練有素的操作員', parent_id: 26)
Master.create(code: '6.0', name: 'Scaffolding', chi_name: '搭棚工作', parent_id: 26)
Master.create(code: '6.1', name: 'Statutory Form (Form 5)', chi_name: '法定表格（表格5', parent_id: 26)
Master.create(code: '6.2', name: 'Working platform fully boarded with railings and toe board', chi_name: '工作平台完全登上欄杆和腳趾板', parent_id: 26)
Master.create(code: '6.3', name: 'Safe access', chi_name: '安全通路', parent_id: 26)
Master.create(code: '7.0', name: 'Plants, Tools and Machinery', chi_name: '植物，工具和機械', parent_id: 26)
Master.create(code: '7.1', name: 'Chainsaw', chi_name: '電鋸', parent_id: 26)
Master.create(code: '7.2', name: 'Grass trimmer / cutter', chi_name: '割草機/切割機', parent_id: 26)
Master.create(code: '7.3', name: 'Blower', chi_name: '送風機', parent_id: 26)
Master.create(code: '8.0', name: 'General', chi_name: '一般', parent_id: 26)
Master.create(code: '8.1', name: 'Ladders with For Access Only Label', chi_name: '梯子有 For Access Only ', parent_id: 26)
Master.create(code: '8.2', name: 'Dangerous goods (e.g. gasoline)', chi_name: '危險品（如汽油）', parent_id: 26)
Master.create(code: '8.3', name: 'First aid bag', chi_name: '急救包', parent_id: 26)
Master.create(code: '8.4', name: 'Fire Extingusiher', chi_name: '滅火器', parent_id: 26)
Master.create(code: '8.0', name: 'General', chi_name: '一般', parent_id: 26)
Master.create(code: '9.0', name: 'Checking of Registration Card', chi_name: '檢查登記卡', parent_id: 26)
Master.create(code: '9.1', name: 'Construction worker registration card', chi_name: '建築工人登記卡', parent_id: 26)
Master.create(code: '9.2', name: 'Green card', chi_name: '綠卡', parent_id: 26)
Master.create(code: '10.0', name: 'Other unsafe act or unsafe condition', chi_name: '其他不安全行為或不安全狀況', parent_id: 26)
Master.create(code: '8.0', name: 'General', chi_name: '一般', parent_id: 26)
Master.create(code: '9.0', name: 'Checking of Registration Card', chi_name: '檢查登記卡', parent_id: 26)
Master.create(code: '9.1', name: 'Construction worker registration card', chi_name: '建築工人登記卡', parent_id: 26)

Master.create(code: '1.0', name: 'Housekeepiong', chi_name: '家務', parent_id: 72)
Master.create(code: '1.1', name: 'Site tidiness', chi_name: '建築工地整潔', parent_id: 72)
Master.create(code: '1.2', name: 'Stacking of material', chi_name: '堆疊的材料', parent_id: 72)
Master.create(code: '1.3', name: 'Projecting nail', chi_name: '突出釘子', parent_id: 72)
Master.create(code: '1.4', name: 'Collection and removal of site wastes', chi_name: '收集和清除場地廢物', parent_id: 72)
Master.create(code: '2.0', name: 'Roads work', chi_name: '道路工作', parent_id: 72)
Master.create(code: '2.1', name: 'Publicity board provided with information correcly provided', chi_name: '宣傳板提供正確提供的信息', parent_id: 72)
Master.create(code: '2.3', name: 'TTA displayed onto the publicity board', chi_name: 'TTA展示在宣傳板上', parent_id: 72)
Master.create(code: '2.4', name: 'Adequate vehicular and pedestrain diversion', chi_name: '充足的車輛和行人分流', parent_id: 72)
Master.create(code: '2.2', name: 'Valid XP displayed onto the publicity board', chi_name: '有效的XP顯示在宣傳板上', parent_id: 72)
Master.create(code: '2.5', name: 'Traffic signs, cones & barrier placed in right position', chi_name: '交通標誌，錐體和障礙物放置在正確的位置', parent_id: 72)
Master.create(code: '2.6', name: 'Quality of traffic signs, cones, lantern & barrier', chi_name: '交通標誌，視錐細胞，燈籠和屏障的質量', parent_id: 72)
Master.create(code: '2.7', name: 'Barriers property interlocked', chi_name: '障礙物業互鎖', parent_id: 72)
Master.create(code: '2.8', name: 'Idling sign board', chi_name: '怠速標誌牌', parent_id: 72)
Master.create(code: '2.9', name: 'Warning lanterns', chi_name: '警告燈籠', parent_id: 72)
Master.create(code: '2.10', name: 'Materials and tools maintain inside the fenced off area', chi_name: '材料和工具保持在圍欄區域內', parent_id: 72)
Master.create(code: '2.11', name: 'Others - Water-filled barriers', chi_name: '其他的 - 充滿水的障礙物', parent_id: 72)
Master.create(code: '3.0', name: 'Personal Protective Equipment', chi_name: '個人保護設備', parent_id: 72)
Master.create(code: '3.1', name: 'Safety helmets', chi_name: '安全頭盔', parent_id: 72)
Master.create(code: '3.2', name: 'Safety Shoes', chi_name: '安全鞋', parent_id: 72)
Master.create(code: '3.3', name: 'Eye goggles', chi_name: '護目鏡', parent_id: 72)
Master.create(code: '3.4', name: 'Ear plugs', chi_name: '耳塞', parent_id: 72)
Master.create(code: '3.5', name: 'Respirateor / dust mask', chi_name: '呼吸器/防塵面罩', parent_id: 72)
Master.create(code: '3.6', name: 'Reflective vest', chi_name: '反光背心', parent_id: 72)
Master.create(code: '3.7', name: 'Safety barness with fall arrestor', chi_name: '帶防墜落裝置的安全帶', parent_id: 72)
Master.create(code: '3.8', name: 'Protective gloves', chi_name: '防護手套', parent_id: 72)
Master.create(code: '3.9', name: 'Others - Personal Protective Equipment', chi_name: '其他-個人保護設備', parent_id: 72)
Master.create(code: '4.0', name: 'Lifting Appliances and Lifting gears', chi_name: '起重設備和起重裝置', parent_id: 72)
Master.create(code: '4.1', name: 'Lifting Applicanes', chi_name: '起重設備', parent_id: 72)
Master.create(code: '4.2', name: 'Lifting appliances Statutory Test and Examination Cert (form 3,4 and 5)', chi_name: '起重設備法定測試及檢驗證書（表格3,4及5）', parent_id: 72)
Master.create(code: '4.3', name: 'Lifting appliances Statutory Inspection Cert (form 1)', chi_name: '起重設備法定檢驗證書（表格1）', parent_id: 72)
Master.create(code: '4.4', name: 'Qualified opertor', chi_name: '合格的操作者', parent_id: 72)
Master.create(code: '4.5', name: 'Lifting gears and slings', chi_name: '起重裝置和吊索', parent_id: 72)
Master.create(code: '4.6', name: 'Others - Lifting Appliances and Lifting gears', chi_name: '其他-起重設備和起重裝置', parent_id: 72)
Master.create(code: '5.0', name: 'Working at height / Above-ground work', chi_name: '在高處工作/地上工作', parent_id: 72)
Master.create(code: '5.1', name: 'Use of proper step platform for above-ground work', chi_name: '使用適當的台階平台進行地上工作', parent_id: 72)
Master.create(code: '5.2', name: 'Working platform fully boarded with railings and toe board', chi_name: '工作平台完全登上欄杆和腳趾板', parent_id: 72)
Master.create(code: '5.3', name: 'Scaffolding', chi_name: '搭棚工作', parent_id: 72)
Master.create(code: '5.4', name: 'Safe access to Scaffolding / working platform', chi_name: '安全通路搭棚工作/工作平台', parent_id: 72)
Master.create(code: '5.5', name: 'Preventive measures against falling objects', chi_name: '防止掉落物體的預防措施', parent_id: 72)
Master.create(code: '5.6', name: 'Others - Working at height / Above-ground work', chi_name: '其他-在高處工作/地上工作', parent_id: 72)
Master.create(code: '6.0', name: 'Excavation / Filling', chi_name: '挖掘/填充', parent_id: 72)
Master.create(code: '6.1', name: 'Barriers / fencing', chi_name: 'barriers / fencing', parent_id: 72)
Master.create(code: '6.2', name: 'Safe access to trench / slope', chi_name: '安全進入溝渠/斜坡', parent_id: 72)
Master.create(code: '6.3', name: 'Shoring to trench', chi_name: '支撐溝', parent_id: 72)
Master.create(code: '6.4', name: 'Form 4', chi_name: '表格4', parent_id: 72)
Master.create(code: '6.5', name: 'Temporay drainage system / silt trapping facilities', chi_name: '臨時排水系統/淤泥捕集設施', parent_id: 72)
Master.create(code: '6.6', name: 'Underground utility protection', chi_name: '地下公用設施保護', parent_id: 72)
Master.create(code: '6.7', name: 'Others - Excavation / Filling', chi_name: '其他-挖掘/填充', parent_id: 72)
Master.create(code: '7.0', name: 'Electricity', chi_name: '電力', parent_id: 72)
Master.create(code: '7.1', name: 'Distributing board', chi_name: '配電板', parent_id: 72)
Master.create(code: '7.2', name: 'Wiring and earthing', chi_name: '電線和接地', parent_id: 72)
Master.create(code: '7.3', name: 'Generator', chi_name: 'Generator', parent_id: 72)
Master.create(code: '7.4', name: 'Others - Electricity', chi_name: '其他-電力', parent_id: 72)
Master.create(code: '8.0', name: 'Plants and Machinery', chi_name: '廠和機械', parent_id: 72)
Master.create(code: '8.1', name: 'Circular saw', chi_name: '圓鋸', parent_id: 72)
Master.create(code: '8.2', name: 'Abrasive wheel', chi_name: '砂輪', parent_id: 72)
Master.create(code: '8.3', name: 'Air compressor', chi_name: '空氣壓縮機', parent_id: 72)
Master.create(code: '8.4', name: 'Arc Wlding machine', chi_name: '弧焊機', parent_id: 72)
Master.create(code: '8.5', name: 'Oxy-acetylene cutting set', chi_name: '氧乙炔切割裝置', parent_id: 72)
Master.create(code: '8.6', name: 'Cold milling equipment', chi_name: '冷銑刨設備', parent_id: 72)
Master.create(code: '8.7', name: 'Earth moving equipment', chi_name: '推土機', parent_id: 72)
Master.create(code: '8.8', name: 'Others - bore machine', chi_name: '其他 - 鑽孔機', parent_id: 72)
Master.create(code: '9.0', name: 'Working in confined space', chi_name: '在密閉空間工作', parent_id: 72)
Master.create(code: '9.1', name: 'Valid permit-to-work displaued in a conspicuous place', chi_name: '地方', parent_id: 72)
Master.create(code: '9.2', name: 'Mechganical ventilation to confined space carried out', chi_name: '進行密閉空間的機械通風', parent_id: 72)
Master.create(code: '9.3', name: 'Worker entering into confined space wear safety harness', chi_name: '進入密閉空間的工作者穿安全帶', parent_id: 72)
Master.create(code: '9.4', name: 'At least 2 stnadby person stationed outside confined space', chi_name: '至少2名待命人員駐留在密閉空間外', parent_id: 72)
Master.create(code: '9.5', name: 'Others - Working in confined space', chi_name: '其他-在密閉空間工作', parent_id: 72)
Master.create(code: '10.0', name: 'Mosquito control', chi_name: '蚊子控制', parent_id: 72)
Master.create(code: '10.1', name: 'Clearing of stagnant water in pits, drains, etc', chi_name: '清除坑，排水溝等中的積水', parent_id: 72)
Master.create(code: '10.2', name: 'Sweeping of water at uneven floor', chi_name: '在不平的地板上清掃水', parent_id: 72)
Master.create(code: '10.3', name: 'Disposal of useless cans, empty lunch boxes', chi_name: '處理無用的罐頭，空的飯盒', parent_id: 72)
Master.create(code: '10.4', name: 'Covering of container and tanks', chi_name: '覆蓋容器和罐', parent_id: 72)
Master.create(code: '10.5', name: 'Disposal of abandoned tyres', chi_name: '廢棄輪胎的處置', parent_id: 72)
Master.create(code: '10.6', name: 'Others - Mosquito control', chi_name: '其他 - 蚊子控制', parent_id: 72)
Master.create(code: '11.1', name: 'Noise control', chi_name: '噪音控制', parent_id: 72)
Master.create(code: '11.1', name: 'Comply with the CNP (works during night time or holiday)', chi_name: '遵守CNP（夜間或假日工作）', parent_id: 72)
Master.create(code: '11.2', name: 'Air compressor and breaker', chi_name: '空氣壓縮機和斷路器', parent_id: 72)
Master.create(code: '12.0', name: 'General', chi_name: '一般', parent_id: 72)
Master.create(code: '12.1', name: 'Any improper ladder in depots/works sites/work vehciles', chi_name: '任何', parent_id: 72)
Master.create(code: '12.3', name: 'Gas cylinders', chi_name: '氣瓶', parent_id: 72)
Master.create(code: '12.4', name: 'Dangerous goods', chi_name: '危險物品', parent_id: 72)
Master.create(code: '12.5', name: 'Dust control', chi_name: '防塵', parent_id: 72)
Master.create(code: '12.6', name: 'First aids box', chi_name: 'First aids box', parent_id: 72)
Master.create(code: '12.7', name: 'Fire Extinguisher', chi_name: '滅火器', parent_id: 72)
Master.create(code: '12.8', name: 'Others - General', chi_name: '其他 - 一般', parent_id: 72)
Master.create(code: '13.0', name: 'Checking of registration card', chi_name: '檢查登記卡', parent_id: 72)
Master.create(code: '13.1', name: 'Construction worker registration card', chi_name: '建築工人登記卡', parent_id: 72)
Master.create(code: '13.2', name: 'Green card', chi_name: '綠卡', parent_id: 72)
Master.create(code: '13.4', name: 'Others - Checking of registration card', chi_name: '其他 - 檢查登記卡', parent_id: 72)
Master.create(code: '14.0', name: 'Other unsafe act or unsafe condition', chi_name: '其他不安全行為或不安全狀況', parent_id: 72)
